service: do-i-need-an-umbrella

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
  environment:
    OPEN_WEATHER_MAP_API_KEY: ${env:OPEN_WEATHER_MAP_API_KEY}

functions:
  app:
    handler: index.handler
    reservedConcurrency: 1
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-stack-output
  - serverless-api-stage

custom:
  webpack:
    webpackConfig: 'be.config.js'
    packager: 'npm'
    excludeFiles: src/**/*.test.js
  output:
    file: ./stack.json
  stageSettings:
    MethodSettings:
      ThrottlingBurstLimit: 1
      ThrottlingRateLimit: 1
