service: do-i-need-an-umbrella

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
  environment:
    OPEN_WEATHER_MAP_API_KEY: ${env:OPEN_WEATHER_MAP_API_KEY}
  resourcePolicy:
    - Effect: Allow
      Principal: '*'
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/*/*
      Condition:
        IpAddress:
          aws:SourceIp:
            - ${env:ALLOWED_IP}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-stack-output

custom:
  webpack:
    webpackConfig: 'be.config.js'
    packager: 'npm'
    excludeFiles: src/**/*.test.js
  output:
    file: ./stack.json
