name: ci

on:
  push:
    branches:
      - '*'

jobs:
  test:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install and test
        run: |
          npm ci
          npm test
        env:
          CI: true
        
  deploy:

    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:

        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '12.x'

        - name: deploy to aws
          run: |
            npm run deploy:be
          env:
            CI: true
            OPEN_WEATHER_MAP_API_KEY: ${{ secrets.OPEN_WEATHER_MAP_API_KEY }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        - name: build the front end
          run: |
            npm run build:fe
          env:
            CI: true    

        - name: deploy fe
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            BRANCH: gh-pages
            FOLDER: dist
            CLEAN: true
            