name: Deploy

on:
  push:
    branches:
      - feature/upload_to_aws
#  pull_request:
#    types: [closed]
#    branches:
#      - master

jobs:
  build:

    runs-on: ubuntu-latest
#    if: github.event.pull_request.merged

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build and deploy to aws
        run: |
          npm ci
          npm run deploy:be
        env:
          CI: true
          OPEN_WEATHER_MAP_API_KEY: ${{ secrets.OPEN_WEATHER_MAP_API_KEY }}
