name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build and deploy to aws
        run: |
          npm ci
          npm test
          npm run deploy:be
          npm run build:fe
        env:
          CI: true
          OPEN_WEATHER_MAP_API_KEY: ${{ secrets.OPEN_WEATHER_MAP_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ALLOWED_IP: ${{ secrets.ALLOWED_IP }}

      - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: ui-tests
            path: /home/runner/work/Do-I-need-an-Umbrella/Do-I-need-an-Umbrella/ui-tests/__image_snapshots__/__diff_output__

      - name: deploy fe
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
